### ISSUE TITLE
[BUG] Response doesn't show up

### ISSUE THREAD

**Issue by duckunz** [Sxvxgee/UnlimitedGPT#34] opened 2023-08-14 04:09 UTC
### Description
When I run this code on jupyter notebook
_"message = api.send_message(
    "What is 1 + 112323?",
    input_mode="INSTANT",
)
print(message.response, message.conversation_id)"_

I got the question sent and answered on chatgpt, but the output on jupyter notebook did not show the response. 

Here is the  output on jupyter notebook

print(message.response, message.conversation_id) e5ced5ac-0c81-46da-afea-c8ca651xxxxx ( It only printed out my conversation id)

- Python version: 3.10.9
- Operating System: MacOS
- UnlimitedGPT version: 0.1.9.2

Thank you

**Comment by im-alihashmi14** [comment] 2023-08-14 05:31
@duckunz It's related to copy paste issue. 
It will only print that is copied to the clipboard. Its happening on MacOS only
I have raised an Issue #33

**Comment by Sxvxgee** [comment] 2023-08-15 12:33
Duplicate of #33. Refer to that issue for updates on this bug.

**Closed by Sxvxgee** 2023-08-15 12:33 UTC
Labels: unconfirmed bug
